"""empty message

Revision ID: 5117f4a37066
Revises: 85312873b8f7
Create Date: 2025-01-06 18:15:18.236349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5117f4a37066'
down_revision = '85312873b8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('cover_image',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cover_image',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
