"""empty message

Revision ID: 85312873b8f7
Revises: 7febedc566ee
Create Date: 2025-01-04 17:13:50.796339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85312873b8f7'
down_revision = '7febedc566ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
